# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(100, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.layout.setContentsMargins(30, 20, 30, 20)
        self.layout.setSpacing(20)
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.addStretch()
        self.label = QtWidgets.QLabel("RSA CIPHER")
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.header_layout.addWidget(self.label, alignment=QtCore.Qt.AlignCenter)
        self.btn_gen_keys = QtWidgets.QPushButton("Generate Keys")
        self.header_layout.addWidget(self.btn_gen_keys, alignment=QtCore.Qt.AlignRight)
        self.layout.addLayout(self.header_layout)
        self.grid = QtWidgets.QGridLayout()
        self.grid.setHorizontalSpacing(30)
        self.grid.setVerticalSpacing(15)
        self.label_2 = QtWidgets.QLabel("Plain Text:")
        self.label_2.setMinimumWidth(80)
        self.grid.addWidget(self.label_2, 0, 0, alignment=QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.txt_plain_text = QtWidgets.QTextEdit()
        self.txt_plain_text.setMinimumHeight(80)
        self.grid.addWidget(self.txt_plain_text, 0, 1)
        self.label_4 = QtWidgets.QLabel("Information:")
        self.label_4.setMinimumWidth(80)
        self.grid.addWidget(self.label_4, 0, 2, alignment=QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.txt_info = QtWidgets.QTextEdit()
        self.txt_info.setMinimumHeight(80)
        self.grid.addWidget(self.txt_info, 0, 3)
        self.label_3 = QtWidgets.QLabel("CipherText:")
        self.label_3.setMinimumWidth(80)
        self.grid.addWidget(self.label_3, 1, 0, alignment=QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.txt_cipher_text = QtWidgets.QTextEdit()
        self.txt_cipher_text.setMinimumHeight(80)
        self.grid.addWidget(self.txt_cipher_text, 1, 1)
        self.label_5 = QtWidgets.QLabel("Signature:")
        self.label_5.setMinimumWidth(80)
        self.grid.addWidget(self.label_5, 1, 2, alignment=QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.txt_sign = QtWidgets.QTextEdit()
        self.txt_sign.setMinimumHeight(80)
        self.grid.addWidget(self.txt_sign, 1, 3)
        self.layout.addLayout(self.grid)
        self.button_layout = QtWidgets.QGridLayout()
        self.btn_encrypt = QtWidgets.QPushButton("Encrypt")
        self.btn_decrypt = QtWidgets.QPushButton("Decrypt")
        self.btn_sign = QtWidgets.QPushButton("Sign")
        self.btn_verify = QtWidgets.QPushButton("Verify")
        self.button_layout.addWidget(self.btn_encrypt, 0, 1)
        self.button_layout.addWidget(self.btn_decrypt, 0, 2)
        self.button_layout.addWidget(self.btn_sign, 0, 3)
        self.button_layout.addWidget(self.btn_verify, 0, 4)
        self.layout.addLayout(self.button_layout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Cipher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
